# -*- coding: utf-8 -*-
"""cv2_imgtosketch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1niJqVdqkgUb-gu0yhk293f6Ul-b8cojz
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt
img=cv2.imread("/content/drive/My Drive/Projects/Elon.jpg")
cv2_imshow(img_rgb)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)

img_invert=cv2.bitwise_not(gray)
cv2_imshow(img_invert)

gblur_img=cv2.GaussianBlur(img_invert,(21,21),sigmaX=0,sigmaY=0)
cv2_imshow(gblur_img)

def dodge_img(x,y):
  return cv2.divide(x,255-y,scale=256)
dodged_img=dodge_img(gray,gblur_img)
cv2_imshow(dodged_img)

def burn_img(image, mask):
  return 255 - cv2.divide(255-image, 255-mask, scale=256)
final_image=burn_img(dodged_img,gblur_img)

cv2_imshow(final_image)

